### ISSUE TITLE
When using two type into answers ("{{type: }}"), Anki ignores the second one, and instead shows two of the first one on the answer screen

### ISSUE THREAD

**Issue by Shidouuu** [ankitects/anki#1401]
###### Reproduction steps
1. Create a new deck and a new card type with a 'Reading' and 'Meaning' field, and add a note.
2. Type something into them.
3. Paste the following into the Front, Back, and CSS (Taken from a modified shared note type so there are probably some parts that are not necessary):

Front:
```html
<span style="font-size: 15vh; ">
<div class=jp> {{furigana:Reading}}</div>

{{type:Reading}}
{{type:Meaning}}
```
Back:
```html
<div id=reading class=jp style="visibility: visible !important; font-size: 15vh;"> {{furigana:Reading}}</div> 

<hr id=answer>
<div style="font-size: 5vh;">{{Meaning}}</div>

<div  style="float: left; display: block; margin-left: 10%;">{{type:Meaning}} </div> 

<div style="float: right; display: block; margin-right: 10%;">{{type:Reading}} </div>
```
CSS:
```css
.card {
 font-family: arial;
 font-size: 32px;
 text-align: center;
 color: black;
 background-color: #d4e7eb;
} 

ruby rt {
visibility: hidden; 
}

ruby:hover rt { 
visibility: visible;
 }
```
4. Go back to 'Decks', and study the deck. Type something into the text boxes.
![image](https://user-images.githubusercontent.com/36283656/135544667-d6ff09bf-df8c-4e39-9a9c-f257b45eec55.png)
5. ???
6. Profit.
![image](https://user-images.githubusercontent.com/36283656/135544915-0737a4d3-bb60-4fd8-814b-3c69ae65d11e.png)
_Oops, maybe there should have been a third field for the reading. Whatever, you get the point._

###### etc
So, the expected result would be two different answers being corrected, but as you can see, it repeats the first one. This is probably more of an unexpected use than a bug; I guess nobody expected someone to use two `{{type: }}`'s.

Using Anki ⁨2.1.48; installed from pip.
