### ISSUE TITLE
CSS animation fails to work after upgrading to 2.1.63

### ISSUE THREAD

**Issue by IceTea233** [ankitects/anki#2499]
I found that the CSS animation in my template doesn't work anymore after the upgrade. Here is my code:

```css
@keyframes flip {
  0% {
    opacity: 0;
    transform: rotate(
20deg) rotateX(180deg) rotateY(-45deg) scale(1.3);
  }
  100% {
    opacity: 1;
  }
}
```

As additional information, I use anki under the environment of Windows 10.

I put this code at the end of the `Back Template` customizing area., and it should make a card "flip" and appear in on the screen. However, the animation seems not to work now. More specifically, the card just appear without any animation after the "showing back part of the card" action is triggered.

I'm not familiar with typescript and also haven't check the problem furthermore yet, but I suspect the behavior was changed in #2356. If this is the the expected change, I would like to receive some recommendations to refactor my configuration.

No matter this is an unexpected change or not, I might come back to review and investigate the change later when I have time.
