### ISSUE TITLE
Images in IO cards too small on mobile

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#2978]
https://github.com/ankidroid/Anki-Android/issues/15235

In landscape mode, the images in native IO notes are too small on a mobile (probably because Anki is trying to fit the image height on the screen?)

In the IO cards made using IOE add-on, the image is large enough to be seen clearly.

The OP mentions that adding the following code to the styling section fixes the issue:

```css
#image-occlusion-canvas {
    --inactive-shape-color: #ffeba2;
    --active-shape-color: #ff8e8e;
    --inactive-shape-border: 1px #212121;
    --active-shape-border: 1px #212121;

    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    width: 100vw;
    height: auto;
    object-fit: contain;
}

.card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}

#image-occlusion-container img {
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    width: 100vw;
    height: auto;
    object-fit: contain;
}
```
