### ISSUE TITLE
:empty CSS Pseudo-Class Not Working in Anki

### ISSUE THREAD

**Issue by huandney** [ankitects/anki#3373]
The CSS pseudo-class :empty does not seem to work as expected within Anki. Elements that should be hidden by this selector are still visible.

Exemple:
`footer:empty {
  display: none;
}`

This behavior was expected to work, as it was discussed in a previous forum thread: [Add support for CSS pseudo-class](https://forums.ankiweb.net/t/add-support-for-css-empty-pseudo-class/20541). Despite the discussion, it appears that the `:empty` selector is still not functioning in the current version of Anki.

**Comment by brishtibheja** [comment]
Do you have a reproduction case? I tested hiding a div using `.class:empty` and it did work.

**Comment by huandney** [comment]
> Do you have a reproduction case? I tested hiding a div using `.class:empty` and it did work.


Thank you for your response!

The issue seems to be related to how Anki processes whitespace and line breaks in the HTML. Here's the intended use case:

```css
footer:empty {
  display: none;
}

footer {
  color: var(--accent-color);
  background-color: transparent;
  font-weight: 550;
  padding: 10px 10px 0 0;
  font-size: 13px;
  border-top: 2px solid #e0e0e0;
  margin-top: auto;
  flex-direction: column;
  overflow-x: hidden;
}
```

And the corresponding HTML template:

```html
<footer>
  {{#Fontes}}<div class="sources">{{Fontes}}</div>{{/Fontes}}
  {{#Notas}}<div class="notes">{{Notas}}</div>{{/Notas}}
  {{#Tags}}<div class="tags">{{Tags}}</div>{{/Tags}}
</footer>
```

The goal is to hide the `<footer>` entirely if none of the three fields (`Fontes`, `Notas`, `Tags`) are populated. However, this doesn't work as expected with `:empty`. Instead, I had to use the following alternatives:

### Workaround 1 (Conditionals):
```html
{{#Notas}}
<footer>
  {{#Fontes}}<div class="sources">{{Fontes}}</div>{{/Fontes}}
  <div class="notes">{{Notas}}</div>
  {{#Tags}}<div class="tags">{{Tags}}</div>{{/Tags}}
</footer>
{{/Notas}}

{{^Notas}}
  {{#Fontes}}
  <footer>
    <div class="sources">{{Fontes}}</div>
    {{#Tags}}<div class="tags">{{Tags}}</div>{{/Tags}}
  </footer>
  {{/Fontes}}

  {{^Fontes}}
    {{#Tags}}
    <footer>
      <div class="tags">{{Tags}}</div>
    </footer>
    {{/Tags}}
  {{/Fontes}}
{{/Notas}}
```

### Workaround 2 (`:has`):
```css
footer:not(:has(.sources, .notes, .tags)) {
  display: none;
}
```
```html
<footer>
  {{#Fontes}}<div class="sources">{{Fontes}}</div>{{/Fontes}}
  {{#Notas}}<div class="notes">{{Notas}}</div>{{/Notas}}
  {{#Tags}}<div class="tags">{{Tags}}</div>{{/Tags}}
</footer>
```

---
Through testing, I discovered that `:empty` works **if the HTML is compact**, without spaces or line breaks between elements:

```html
<footer>{{#Fontes}}<div class="sources">{{Fontes}}</div>{{/Fontes}}{{#Notas}}<div class="notes">{{Notas}}</div>{{/Notas}}{{#Tags}}<div class="tags">{{Tags}}</div>{{/Tags}}</footer>
```

It seems that Anki inserts line breaks or whitespace into the DOM, which makes the `<footer>` non-empty from the perspective of the `:empty` selector. I don't know if this is standard behavior, or if it's really an error.
