### ISSUE TITLE
Giant sync icon sometimes appears

### ISSUE THREAD

**Issue by dae** [ankitects/anki#983]
Some users have reported the following issue:

https://forums.ankiweb.net/t/bug-huge-sync-icon-in-main-window/4048/8

It appears to happen on both Linux and Windows. I have never come across it, but my primary development machine is a Mac. The fact that there were no errors when running with ANKIDEV=1 seems to imply the request is never being made or never being received. Someone who experiences it on their local machine may be able to look into it further, perhaps trying to reload the page multiple times in the Chrome dev tools, adding more instrumenting to mediasrv.py, etc.

**Comment by RumovZ** [comment]
I regularly encounter this when developing, it even seems to happen more frequently now than compared to a few months ago. However, I have never had the issue when launching the binaries. When running from source I don't have a way to reproduce it reliably, either, but rerunning a couple of times usually does the trick.
Once the issue has occured, nothing except restarting seems to help.

I'm not proficient in web development or Anki's webview code, so I have no idea how to go about debugging. Sending the file in `mediarsv.py` seems successful to me and reloading in Chrome DevTools does nothing to the missing css.
If you want me to try anything just let me know.

**Comment by dae** [comment]
Does running with ./scripts/runopt make a difference to how often it happens? Wondering if it's a race condition

Does the css file show up in the list of page resources when viewing the buggy page with the devtools?

**Comment by RumovZ** [comment]
> Does running with ./scripts/runopt make a difference to how often it happens? Wondering if it's a race condition

That will be hard to quantify, but I just gave it a go and immediately encountered the issue.

> Does the css file show up in the list of page resources when viewing the buggy page with the devtools?

No, there's no css at all, but I just realised, if I inspect the bottom toolbar page, there is not only `toolbar-bottom.css`, but also `toolbar.css` and `webview.css`.

**Comment by dae** [comment]
The top area should have toolbar.css and webview.css when viewing the Sources tab:
<img width="287" alt="Screen Shot 2021-03-16 at 9 02 33 pm" src="https://user-images.githubusercontent.com/180542/111298913-0f51bd00-869b-11eb-8e16-1610f518c637.png">

Neither of those are showing up, but they show up in the requests with ANKIDEV? Is _onHeight() being called for the top toolbar? Does commenting out acceptNavigationRequest make any difference? Any difference when loading a profile directly vs opening up the profiles screen first?

**Comment by RumovZ** [comment]
> Neither of those are showing up, but they show up in the requests with ANKIDEV?

Exactly:

![grafik](https://user-images.githubusercontent.com/48286681/111299955-d68cf600-8650-11eb-8fe9-1c64d1fdd8ec.png)

> Is _onHeight() being called for the top toolbar?

It gets called the same number of times, twice for loading the main page. Only the arguments differ (not surprising, I assume).
Broken (one example, height is not uniform here):
![grafik](https://user-images.githubusercontent.com/48286681/111301399-76974f00-8652-11eb-8b99-6ab7abeac1dd.png)
Ok:
![grafik](https://user-images.githubusercontent.com/48286681/111301443-81ea7a80-8652-11eb-8a91-152d7a2aa9d1.png)

> Does commenting out acceptNavigationRequest make any difference?

Where do I do that? I tried returning immediately in `webview.py/acceptNavigationRequest()`, that didn't make a difference.

> Any difference when loading a profile directly vs opening up the profiles screen first?

It seems that way. I got the issue the first time I ran with a profile name, but not once in my countless trials after that, even when I started switching the profile at runtime.
It never takes more than a few trials to trigger the issue when I run without the p paramter, so I think it could be called statistically significant.

**Comment by dae** [comment]
The (no domain) section has two entries, but I'm only seeing one. Do you see only one entry when the problem doesn't occur? I wonder what the colour represents? Was the same text returned both times? If you comment out the .redraw() line in the deck browser, does that fix it? Maybe we're loading the HTML, then loading it again before the first load finishes, resulting in a partially loaded page.

**Comment by RumovZ** [comment]
Indeed, the violet entry only seems to occur when the CSS is missing. The two files show different ports then.
According to [this answer](https://stackoverflow.com/questions/43599974/why-does-chrome-devtools-show-these-folders-in-orange-and-in-italics), violet means CSS and grey means HTML. Curious.

```HTML
<!doctype html>
<html class="">
<head>
    <title>top toolbar</title>
<base href="http://127.0.0.1:55000/"><link rel="stylesheet" type="text/css" href="http://127.0.0.1:55000/_anki/css/webview.css"><style>
body { zoom: 1; background: #f0f0f0; direction: ltr; font-size:12px;font-family:"Segoe UI"; }
button { font-family:"Segoe UI"; }
:focus { outline: 1px solid #0078d7; }
:root { --window-bg: #f0f0f0 }
:root[class*=night-mode] { --window-bg: #f0f0f0 }
</style><link rel="stylesheet" type="text/css" href="http://127.0.0.1:55000/_anki/css/toolbar.css"><script src="http://127.0.0.1:55000/_anki/js/webview.js"></script>
<script src="http://127.0.0.1:55000/_anki/js/webview.js"></script>
<script src="http://127.0.0.1:55000/_anki/js/vendor/jquery.min.js"></script>
<script src="http://127.0.0.1:55000/_anki/js/toolbar.js"></script>
</head>

<body class="isWin">
<center id=outer>
<table id=header width=100%>
<tr>
<td class=tdcenter align=center><a class=hitem tabindex="-1" aria-label="Decks" title="Shortcut key: ⁨D⁩" id="decks" href=# onclick="return pycmd('decks')">Decks</a>
<a class=hitem tabindex="-1" aria-label="Add" title="Shortcut key: ⁨A⁩" id="add" href=# onclick="return pycmd('add')">Add</a>
<a class=hitem tabindex="-1" aria-label="Browse" title="Shortcut key: ⁨B⁩" id="browse" href=# onclick="return pycmd('browse')">Browse</a>
<a class=hitem tabindex="-1" aria-label="Stats" title="Shortcut key: ⁨T⁩" id="stats" href=# onclick="return pycmd('stats')">Stats</a>

<a class=hitem tabindex="-1" aria-label="Sync" title="Shortcut key: ⁨Y⁩" id="sync" href=# onclick="return pycmd('sync')">Sync
<img id=sync-spinner src='/_anki/imgs/refresh.svg'>        
</a></td>
</tr></table>
</center>
</body>
</html>
```
```HTML
<!doctype html>
<html class="">
<head>
    <title>top toolbar</title>
<base href="http://127.0.0.1:54822/"><link rel="stylesheet" type="text/css" href="http://127.0.0.1:54822/_anki/css/webview.css"><style>
body { zoom: 1; background: #f0f0f0; direction: ltr; font-size:12px;font-family:"Segoe UI"; }
button { font-family:"Segoe UI"; }
:focus { outline: 1px solid #0078d7; }
:root { --window-bg: #f0f0f0 }
:root[class*=night-mode] { --window-bg: #f0f0f0 }
</style><link rel="stylesheet" type="text/css" href="http://127.0.0.1:54822/_anki/css/toolbar.css"><script src="http://127.0.0.1:54822/_anki/js/webview.js"></script>
<script src="http://127.0.0.1:54822/_anki/js/webview.js"></script>
<script src="http://127.0.0.1:54822/_anki/js/vendor/jquery.min.js"></script>
<script src="http://127.0.0.1:54822/_anki/js/toolbar.js"></script>
</head>

<body class="isWin">
<center id=outer>
<table id=header width=100%>
<tr>
<td class=tdcenter align=center><a class=hitem tabindex="-1" aria-label="Decks" title="Shortcut key: ⁨D⁩" id="decks" href=# onclick="return pycmd('decks')">Decks</a>
<a class=hitem tabindex="-1" aria-label="Add" title="Shortcut key: ⁨A⁩" id="add" href=# onclick="return pycmd('add')">Add</a>
<a class=hitem tabindex="-1" aria-label="Browse" title="Shortcut key: ⁨B⁩" id="browse" href=# onclick="return pycmd('browse')">Browse</a>
<a class=hitem tabindex="-1" aria-label="Stats" title="Shortcut key: ⁨T⁩" id="stats" href=# onclick="return pycmd('stats')">Stats</a>

<a class=hitem tabindex="-1" aria-label="Sync" title="Shortcut key: ⁨Y⁩" id="sync" href=# onclick="return pycmd('sync')">Sync
<img id=sync-spinner src='/_anki/imgs/refresh.svg'>        
</a></td>
</tr></table>
</center>
</body>
</html>
```

Commenting out the redraw line doesn't help.

**Comment by dae** [comment]
I'd expect the port numbers to change over multiple program invocations, but are you saying they were different in the first and second request in a single Anki session? Does setting the env var ANKI_API_PORT  to 40000 change the behaviour at all?

**Comment by RumovZ** [comment]
Yes, those are the files from a single Anki session. At least I thought that. Now when I try that again, the second file looks like this:

```CSS
:root{--text-fg: black;--window-bg: #ececec;--frame-bg: white;--border: #aaa;--medium-border: #b6b6b6;--faint-border: #e7e7e7;--link: #00a;--review-count: #0a0;--new-count: #00a;--learn-count: #c35617;--zero-count: #ddd;--slightly-grey-text: #333;--highlight-bg: #77ccff;--highlight-fg: black;--disabled: #777;--flag1-fg: #c35617;--flag2-fg: #ffb347;--flag3-fg: #0a0;--flag4-fg: #77ccff;--flag1-bg: #ffaaaa;--flag2-bg: #ffb347;--flag3-bg: #82e0aa;--flag4-bg: #85c1e9;--buried-fg: #aaaa33;--suspended-fg: #dd0;--suspended-bg: #ffffb2;--marked-bg: #cce;--tooltip-bg: #fcfcfc}:root[class*=night-mode]{--text-fg: white;--window-bg: #2f2f31;--frame-bg: #3a3a3a;--border: #777;--medium-border: #444;--faint-border: #29292b;--link: #77ccff;--review-count: #5ccc00;--new-count: #77ccff;--learn-count: #ff935b;--zero-count: #444;--slightly-grey-text: #ccc;--highlight-bg: #77ccff;--highlight-fg: white;--disabled: #777;--flag1-fg: #ffaaaa;--flag2-fg: #ffb347;--flag3-fg: #82e0aa;--flag4-fg: #85c1e9;--flag1-bg: #aa5555;--flag2-bg: #aa6337;--flag3-bg: #33a055;--flag4-bg: #3581a9;--buried-fg: #777733;--suspended-fg: #ffffb2;--suspended-bg: #aaaa33;--marked-bg: #77c;--tooltip-bg: #272727}*{box-sizing:border-box}body{font-family:Helvetica,Arial;color:var(--text-fg);background:var(--window-bg);margin:1em}a{color:var(--link);text-decoration:none}.isWin button{font-size:12px}.isMac button{font-size:13px}.isLin button{font-size:14px;-webkit-appearance:none;border-radius:3px;padding:5px;border:1px solid var(--border)}.nightMode button{-webkit-appearance:none;color:var(--text-fg);background:linear-gradient(0deg, #555555 0%, #656565 100%);box-shadow:0 0 3px #222;border:1px solid #646464;border-radius:2px;padding:10px;padding-top:3px;padding-bottom:3px}.nightMode button:hover{background:#656565}.isMac.nightMode.macos-dark-mode button:not(.linkb){background:#656565;box-shadow:0 1px 2px #222;border-top-color:#848484;border-top-width:.5px;border-bottom:0;border-left:0;border-right:0;padding-top:2px;padding-bottom:2px;padding-left:15px;padding-right:15px;color:#e5e5e5}*{box-sizing:content-box}body{margin:2em;overscroll-behavior:none}h1{margin-bottom:.2em}.nightMode::-webkit-scrollbar{background:var(--window-bg)}.nightMode::-webkit-scrollbar:horizontal{height:12px}.nightMode::-webkit-scrollbar:vertical{width:12px}.nightMode::-webkit-scrollbar-thumb{background:#656565;border-radius:8px}.nightMode::-webkit-scrollbar-thumb:horizontal{min-width:50px}.nightMode::-webkit-scrollbar-thumb:vertical{min-height:50px}
```

The two files look the same in Chrome, but I think Chrome is getting confused because they have the same name and always opens the first. What I've posted here is what I see when I download the files and open them in Notepad.
Now I'm wondering if I made a mistake yesterday. That would explain why one is coloured violet because it really contains CSS whereas the other one with the same name contains HTML.

I assume ANKI_API_PORT is an environment variable? Setting it doesn't seem to make a difference.
